### ISSUE TITLE
Scheduler incorrect date

### ISSUE THREAD

**Issue by jaketame** [nosmokingbandit/Watcher3#130]
I have some Waiting/Wanted movies in the queue however they are not scanning;
The date shown for next scan is in the past;
Nothing found yet. Next search sheduled for Saturday, Sep 23, at 00:58.

Current datetime is: Fri Sep 29 13:58:37 BST 2017

**Comment by nosmokingbandit** [comment]
Sorry for the delayed response, I was reinstalling all of my server from scratch (long story).

We may have to dig around a bit to see what the deal is. Can you post the contents of `watcher/core/cp_plugins/tasks.json`? At what interval do you have the scan set to? I'll try to recreate it on my server.

**Comment by jaketame** [comment]
I'm running Docker (Watcher) updated automatically and its now displaying the correct date. When I look at a waiting/wanted movie;

```
root@5e848b9f4a6a:/app/watcher/core/cp_plugins$ cat tasks.json
{
    "IMDB Sync": {
        "lastexecution": "2017-08-05 23:58:45"
    },
    "Metadata Update": {
        "lastexecution": "2017-09-20 23:58:07"
    },
    "Movie Search": {
        "lastexecution": "2017-09-22 23:58:07"
    },
    "PopularMovies Sync": {
        "lastexecution": "2017-09-22 23:58:07"
    },
    "PostProcessing Scan": {
        "lastexecution": "2017-10-02 06:28:42"
    },
    "Trakt Sync": {
        "lastexecution": "2017-09-20 23:58:07"
    },
    "Update Checker": {
        "lastexecution": "2017-09-22 23:59:07"
    }
```

**Comment by jaketame** [comment]
Docker Volumes:
    volumes:
      - /opt/apps/watcher:/config
      - /opt/apps/watcher/posters:/app/watcher/static/images/posters
      - /data/downloads:/data/downloads
      - /data/media/movies:/data/media/movies

Maybe I need to add one directly for the tasks.json or move that information into the DB?

**Comment by nosmokingbandit** [comment]
I don't know anything about how docker handles files. The tasks.json file is created and managed automatically, the user should never need to know it exists (unless something goes wrong).

Post-processing scan did update to "2017-10-02 06:28:42", as you can see, so that is at least working somewhat correctly.

Check out `tasks.json` again, then immediately go to `<watcher_url>/settings/system` and run PostProcessing Scan. Then check to see if `tasks.json` is updated to the current time, and if not send a copy of your logs to `watchernzb@gmail.com`

**Comment by jaketame** [comment]
Looks like its resolved itself. Its now grabbing correctly. Cheers

**Comment by jaketame** [comment]
Looks like this issue is back


Enabled | Name | Frequency | Last Execution | Next Execution | Execute Now
-- | -- | -- | -- | -- | --
  | Movie Search | 1 Hours | 6 days ago | -- |  
  | Update Checker | 24 Hours | 6 days ago | -- |  
  | IMDB Sync | 1 Hours | 72 days ago | -- |  
  | Metadata Update | 72 Hours | 7 days ago | -- |  
  | PopularMovies Sync | 24 Hours | 6 days ago | -- |  
  | PostProcessing Scan | 15 Minutes | 6 days ago | -- |  
  | Trakt Sync | 60 Hours | 7 days ago | -- |

**Comment by nosmokingbandit** [comment]
Can you send me all of your log files? `watchernzb@gmail.com`

I can't reproduce this so I'm not 100% sure what is going on. Or even 0% sure.

**Comment by jaketame** [comment]
I've sent over the logs.

Some notes

1) Running inside Docker
2) The Enabled tab is not displaying any Ticks for the Tasks.
3) I noticed there was what appeared to be a plugin that requires persistent storage /watcher/core/cp_plugins. I have since moved this to persistent storage, restarted watcher and now the tasks show correctly enabled. I will monitor and report back.

**Comment by nosmokingbandit** [comment]
Just wanted to give you a heads up, I have a pretty good sized update I
might push out tonight that should resolve all of this forever. Basically
I'll keep the schedule record in the database rather than a separate file,
so as long as your database exists (which is has to or Watcher won't start)
it will always have the necessary info.

**Comment by jaketame** [comment]
Apologies I didn't respond sooner, sorry it was such a headache for you its
a strange one. All the tasks were showing as not enabled again even after
moving to persistent storage so not quite sure whats up there.

I do manually map the posters to persistent storage as I did experience
loss of posters and had to re-fetch them all.

Thanks for all your hard work, its much appreciated. I wish I had more time
to contribute from a coding perspective.

Regards,

Jake

**Comment by nosmokingbandit** [comment]
Part of the problem is that I don't know a damn thing about Docker. From
what I've read it seems as though you have to specify any files that are
created as persistent or it deletes them whenever it is in the mood. What I
did was set it up so all files that are created (config, database, posters,
etc) are in watcher/userdata/. I suppose the docker container creator would
have to set up persistent storage on that dir, but at least it is one dir
that is easy to manage. It also made my backup script about half as long
since all I need to do now is zip that folder.

As far as the scheduler goes... It is complicated. I wrote the whole thing
myself since I couldn't find any good scheduling solutions without adding
tons of bloat or not working the way I want. Part of the challenge was
setting up persistence. For example, every 72 hours Watcher checks for
metadata updates for movies that don't have a release date, are missing
posters, etc. But if I set it up to run every 72 hours starting after
launch it might not ever run if the user restarts or if I push out updates
more often than 72 hours. So the plan was to create a persistence file,
which is just a dict containing the name of the task and last execution ie
{"task": "Metadata Update", "last_execution": "2017-10-25 22:15:20"}. Then
when Watcher starts it checks this dict and sets Metadata Update to run 72
hours after the last_execution. This way the frequency is kept sane and I
can use this to calculate the next execution time in settings/system. The
problem is that writing all of this to tasks.json only works if that file
stays put and Docker doesn't know that I kind of need that. So I set up the
scheduler to be able to write to the database and made a table TASKS just
for that purpose. Then execution times are read/written to the db and are
always handy.

I hope that makes any amount of sense.

Regardless, after updating to
https://github.com/nosmokingbandit/Watcher3/commit/b7c85a8f65d22fd1ce4acd3f73e82c060ed258f7
let me know if  things work as expected. I can't think of anything else
that could cause issues, but that often doesn't work in my favor.

**Comment by jaketame** [comment]
The move into the database has maintained correct schedule dates and execution now so topwork as always! Thanks
