### ISSUE TITLE
Transmission PP script issue

### ISSUE THREAD

**Issue by barbequesauce** [nosmokingbandit/Watcher3#244]
Running current commit (536doe) on Raspbian Jessie with Python 3.4.2.

Trying to get my Transmission PP script working instead of folder monitor. I get a traceback when Transmission executes it... nothing appears in Watcher3's logs.

```
Traceback (most recent call last):
  File "watcher3.py", line 56, in <module>
    response = json.loads(urlopen(request, timeout=600).read().decode('utf-8'))
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

**Comment by nosmokingbandit** [comment]
The 404 error means the script is connecting to a server, just not to a valid url. Watcher doesn't log 404 errors because there isn't much we can learn about a page not existing.

Copy whatever you have as your `watcheraddress` in the script, enter it in your browser, and add `/postprocessing/` to it. For example, attempt to open the page `http://localhost:9090/postprocessing/`

If it is correct it will return `{"response": false, "error": "missing key: apikey"}`, if not you'll get an error page. If you use a custom webroot you have to include this as well, ie `http://localhost:9090/watcher/postprocessing`

**Comment by nosmokingbandit** [comment]
The important bit of that error will be on the Watcher side, the post script is just complaining that it didn't get a proper response.

Its pretty rare to find compressed torrents and usenet clients decompress before other processing, so I never bothered with decompression logic.

A quick glance at pypi makes it look like decompressing rars in python is a bit of an adventure. If that can be easily done and is compatible cross-platform it should be relatively easy to unpack the files first in the post-processing sequence then scan the extracted files for the actual movie. I'll take a closer look at it sometime soon.
