### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by WilliamJBrown** [nosmokingbandit/Watcher3#60]
Got another one for you, 

Cannot login and the logs are calling for successful login.

`INFO 2017-06-09 20:38:32,682 core.auth.on_login: Successful login from x.x.x.x

INFO 2017-06-09 20:38:38,322 core.auth.on_login: Successful login from x.x.x.x

INFO 2017-06-09 20:39:56,970 core.auth.on_login: Successful login from x.x.x.x

INFO 2017-06-09 20:40:02,416 core.auth.on_login: Successful login from x.x.x.x

INFO 2017-06-09 20:41:59,696 core.auth.on_login: Successful login from x.x.x.x

INFO 2017-06-09 20:43:44,768 core.auth.on_login: Successful login from x.x.x.x`

Not sure whats happening might be something with my specific setup.

**Comment by nosmokingbandit** [comment]
Hmmmm. Login seems to work fine for me. Are you on the `/auth` page when you log in or a different url?

The page just refreshes after login, so if you are on `/auth` it will keep you at the login page even though you are logged in and the rest of the pages are available. Have you tried manually going to `/library/status` after logging in?

You can try clearing your cookies for your Watcher url and trying again. In Chrome click the (i) next to the url, then cookies, and remove localhost>cookies>session. If you use a different browser you are on your own.

After d6252695a755355addcc44f0406d962add508439 `/auth` will redirect to `/library/status` after login rather than itself, so if that it the problem it won't happen again.

**Comment by WilliamJBrown** [comment]
Everything is working great now. I just checked it out again. 

Thanks for everything! :) You are the best.
