### ISSUE TITLE
manual download of posters

### ISSUE THREAD

**Issue by jaketame** [nosmokingbandit/Watcher3#81]
I've migrated watcher directory to a new server and posters are now all blank... Anyway to force the redownload of them?

Cheers

**Comment by nosmokingbandit** [comment]
The backup script makes a copy of all of the posters and will restore them. Assuming you used it, does the zip it created contain a `posters` folder? If so and it didn't restore correctly you can copy it manually to `watcher/static/images/posters`

Otherwise you can go to `localhost:9090/library/manage` , select all movies, and update the metadata. It will trigger a poster re-download.

**Comment by jaketame** [comment]
Thanks muchly!
