### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by jaketame** [nosmokingbandit/Watcher3#87]
Some ideas;

- Ability to set default sorting and view on status page (It forgets between web/mobile sometimes)
- Ability to hide Finished items on Ststus page and a config setting for this.
- revamp of plugins page, ability to import via web page.

**Comment by nosmokingbandit** [comment]
1) It stores the UI state in a cookie. This way you should be able to have your phone stay on compact view and your desktop on posters without having to switch every time you switch devices. There may be some weirdness with this related to the other issue you posted about docker not jiving with cookies.

2) Someone else asked about that a while ago and I just plain forgot about it.

3) I have a loosely-formed plan to completely redo all plugin-related things, but I wanted to take some time to focus on bugfixes rather than features for a bit. The plugins frontend was rushed and I never really got back to it.

**Comment by jaketame** [comment]
1) Now resolved based on other commit.
2/3) Let me know your idea and I can maybe help?

**Comment by nosmokingbandit** [comment]
I'm always bad at explaining things.

For hiding Finished movies -- The server sends the browser a total count of the library size so we know how many pages are available, so that will need to have a condition to get just the count of non-Finished or Disabled movies (Disabled being the name used internally for movies that were manually set to 'Finished'). 

So I'd want to send the browser the total count and the non-finished count so there can be a tag at the bottom like "Not showing 147 Finished movies"

Then when the browser asks for a new page of movies to show the server will have to pick out the next 50 non-finished movies and return them.

Not super complicated, just a bunch of things to keep track of. If you want to take a crack at it I'm happy to take pull requests.


As far as plugins... That would take a lot of space to explain. I'm going to tackle that soon anyway.

**Comment by nosmokingbandit** [comment]
> Ability to hide Finished items on Status page and a config setting for this.

Done in afbf69df6f7ec583adbf6e95e1638c73d4404265.
