### ISSUE TITLE
SSL Certs path

### ISSUE THREAD

**Issue by DraZtiK** [nosmokingbandit/Watcher3#98]
Is it possible to allow paths for SSL certs in the same fashion that Couchpotatoserver allowed?

Also, A way to donate? I feel as if Couchpotato is at a stage that just no longer works well, I tried Radarr and requires a lot of work to get it to run under Linux with it requiring Mono. Radarr is also resource hungry.

Watcher is fantastic! An option for some to show their appreciation would be great.

**Comment by nosmokingbandit** [comment]
Cherrypy seems to have pretty easy ssl cert support, so I'll take a good look at it soon. I have a few bugs and things to take care of first.

As far as donations.... I've been fairly opposed to accepting donations. I don't want to be in a position where I'm 'selling' this to get donations, nor do I want to feel obligated to add features based on donations. There is a certain amount of freedom that comes from being 100% independent. My thoughts may change in the future, but for now I'm not entertaining donations.

**Comment by DraZtiK** [comment]
Thanks for taking the time to look into it. Assuming it has support enabled for SSL. Where should the certs be stored and named currently? Option "Verify SSL Certificates" doesn't seem to work? I receive error "SSL_ERROR_RX_RECORD_TOO_LONG" after trying to connect via https.

**Comment by nosmokingbandit** [comment]
b4b83d1bec5035c8ef4665ce7f454044455d9dce lets you supply your own cert.

The verify option is for outgoing connections. The wiki explains it so I'm not going to type it all out again.

I added a method to redirect from `http` to `https` when you have a cert/key supplied, but it stopped working for me and I'm not sure when/why. I originally had redirects as 301 rather than 302, so that might have caused something stupid. Let me know how it works for you.

**Comment by DraZtiK** [comment]
After supply the path to the my self signed certs I received the error.
<pre>
 2017-07-20 09:10:02,413 __main__.<module>: SSL Certs are enabled. Server will only be accessible via https.
INFO 2017-07-20 09:10:02,415 cherrypy.error.error: [20/Jul/2017:09:10:02] ENGINE Listening for SIGHUP.
INFO 2017-07-20 09:10:02,415 cherrypy.error.error: [20/Jul/2017:09:10:02] ENGINE Listening for SIGUSR1.
INFO 2017-07-20 09:10:02,415 cherrypy.error.error: [20/Jul/2017:09:10:02] ENGINE Listening for SIGTERM.
INFO 2017-07-20 09:10:02,415 cherrypy.error.error: [20/Jul/2017:09:10:02] ENGINE Bus STARTING
INFO 2017-07-20 09:10:02,418 cherrypy.error.error: [20/Jul/2017:09:10:02] ENGINE Forking once.
INFO 2017-07-20 09:10:02,420 cherrypy.error.error: [20/Jul/2017:09:10:02] ENGINE Forking twice.
INFO 2017-07-20 09:10:02,421 cherrypy.error.error: [20/Jul/2017:09:10:02] ENGINE Daemonized to PID: 25278
INFO 2017-07-20 09:10:02,545 cherrypy.error.error: [20/Jul/2017:09:10:02] ENGINE Serving on https://0.0.0.0:9292
INFO 2017-07-20 09:10:02,545 cherrypy.error.error: [20/Jul/2017:09:10:02] ENGINE Bus STARTED
ERROR 2017-07-20 09:10:02,561 cherrypy.error.error: [20/Jul/2017:09:10:02] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/local/sbin/Watcher3/lib/cheroot/server.py", line 1466, in start
    self.tick()
  File "/usr/local/sbin/Watcher3/lib/cheroot/server.py", line 1541, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/local/sbin/Watcher3/lib/cheroot/ssl/builtin.py", line 73, in wrap
    server_side=True)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
</pre>

**Comment by DraZtiK** [comment]
It DOES work though. Just a lot of errors in the log. Similar to [https://github.com/sabnzbd/sabnzbd/issues/820](url)

**Comment by nosmokingbandit** [comment]
FYI, pyopenssl doesn't log near as many errors. Cherrypy can use either the built-in or pyopenssl module, but it has to be enabled manually. I'm going to work on a way to detect and enable pyopenssl if possible and fall back to the built-in ssl module if it isn't. I'll try to remember to post here when it is done, but since everything is technically working fine it isn't high on my to-do list.

**Comment by nosmokingbandit** [comment]
@DraZtiK 
69a5f149ac7a28564bddee0384ecc09cd09ec071

If you have pyopenssl installed it will load that instead of using CherryPy's built-in module. This should eliminate the excessive logging. If you don't have pyopenssl it will fall back to the built-in, so you don't need to configure Watcher at all.
